### ISSUE TITLE
It worked on the same 15 inch razerblade but with Nvidia GPU? 

### ISSUE THREAD

**Issue by Gimel12** [hrytskivr/rba-hackintosh#1]
Hi, 
I have the same laptop just the i7 9gen version but with the rtx 2070 on it, it will work the same? 

How much can you charge if I would like you to help me trough video conference setting it up? 

Thanks in advance

**Comment by hrytskivr** [comment]
Hi different CPU means you'll have to use different SMBIOS, also some other sections could be different.

I'm not going to set it up for you, you should really try and walk your way through the guides I've mentioned, if you stuck with anything go for reddit/discord, people will help you, for free, just don't expect anyone to just make it from 0 to 100 for you.

Good luck!
