### ISSUE TITLE
Install error - An error occurred while verifying firmware

### ISSUE THREAD

**Issue by skull-01** [hrytskivr/rba-hackintosh#2]
Hi, 
I read the guide for open core, made my plist, tried your plist, tried Mojave and Catalina but i can never get a successful install.
I always get an error message that says "An error occurred while verifying firmware".
Any tips on what i am missing?

**Comment by hrytskivr** [comment]
Hello @skull-01, I've run into same problem today, when I tried to do install on new ssd drive, I think it's because of MBP15,2 (board) and MBP15,3 (everything else). I will verify and reply in some time if that'll fix it.

**Comment by hrytskivr** [comment]
@skull-01, indeed that ^^ was the case, fixed in https://github.com/hrytskivr/rba-hackintosh/commit/4aca8c70fd4a0b89740cb9c1541347af6b270df8
