### ISSUE TITLE
External screen

### ISSUE THREAD

**Issue by DocSystem** [hrytskivr/rba-hackintosh#3]
What dGPU do you have?
I have a Razer Blade 15 with RTX 2060 but I can't get external screens working! How did you do?

**Comment by hrytskivr** [comment]
@DocSystem GTX 1060.
RTX cards are not supported after macOS High Sierra, so for external screen to work via HDMI you can't.
However you can output via usb-c cable, but for that to work you'll have to edit SMBIOS to MacBookPro15,2 (and related properties in PlatformInfo obviously).

**Comment by hrytskivr** [comment]
@DocSystem fixed in 8375c63.

**Comment by DocSystem** [comment]
Is it working on 2019 model?
